# railway.toml - Railway configuration file
[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn web_app:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "never"

[env]
PORT = { default = "8000" }